social_network/apps/account/urls.py
from django.urls import path
from django.contrib.auth import views as standart_views

from . import views

app_name = 'account'
urlpatterns = [
    path('account/', views.user_account, name = 'user_account'),
    path('account_setting/', views.account_setting, name = 'account_setting'),
    path('friends/', views.friends, name = 'friends'),
    path('friend_request/', views.friend_request, name = 'friend_request'),
    path('id<int:account_id>/add_friend', views.add_friend, name = 'add_friend'),
    path('id<int:account_id>/add_follower', views.add_follower, name = 'add_follower'),
    path('confirm_friend<int:account_id>/', views.confirm_friend, name = 'confirm_friend'),
    path('delete_friend<int:account_id>/', views.delete_friend, name = 'delete_friend'),
    path('delete_follower<int:account_id>/', views.delete_follower, name = 'delete_follower'),
    path('users/', views.find_users, name = 'find_users'),
    path('id<int:account_id>/', views.account, name = 'account'),
    ]

social_network/apps/bots/urls.py
from django.urls import path

from . import views

app_name = 'bots'
urlpatterns = [
    path('create_post/', views.create_post, name = 'create_post'),
    ]

social_network/apps/dialogs/urls.py
from django.urls import path
from django.contrib.auth import views as standart_views

from . import views

app_name = 'dialogs'
urlpatterns = [
    path('dialog/<str:username>/', views.dialog, name = 'dialog'),
    path('dialog/<str:reciever_name>/leave_message/', views.leave_message, name = 'leave_message'),
    path('messages/', views.messages, name = 'messages'),
    path('post<str:username>/', views.post, name = 'post'),
    path('new_messages/', views.new_messages, name = 'new_messages'),
    path('message<int:message_id>/delete/', views.delete_message, name = 'delete_message'),
    path('dialog<int:companion_id>/delete/', views.delete_dialog, name = 'delete_dialog'),
    ]

social_network/apps/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('delete<int:post_id>/', views.delete_post, name = 'delete_post'),
    path('edit_post<int:post_id>/', views.edit_post, name = 'edit_post'),
    path('news/', views.news, name = 'news'),
    path('like_news/', views.like_news, name = 'like_news'),
    path('friend_news/', views.friend_news, name = 'friend_news'),
    path('news/like/', views.like_or_dislike, name = 'like_or_dislike'),
    path('news/user_like', views.user_like, name = 'user_like'),
    path('news<int:post_id>/leave_comment', views.leave_comment, name = 'leave_comment'),
    path('comment<int:comment_id>/delete', views.delete_comment, name = 'delete_comment'),
    path('news<int:post_id>/', views.post, name = 'post'),
    path('back/', views.back, name = 'back'),
]

social_network/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('registration.urls')),
    path('', include('account.urls')),
    path('', include('dialogs.urls')),
    path('', include('posts.urls')),
    path('', include('bots.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social_network/apps/bots/models.py
from django.db import models

# Create your models here.

social_network/apps/dialogs/models.py
from django.db import models
from django.contrib.auth.models import User


class Message(models.Model):
    sender = models.ForeignKey(User, on_delete = models.DO_NOTHING)
    reciever = models.ForeignKey(User, related_name = 'to_reciever', on_delete = models.DO_NOTHING)
    message_text = models.TextField('Текст сообщения')
    message_image = models.ImageField('Изображение', blank = True, upload_to = 'images/messages/')
    message_time = models.DateTimeField('Время отправления')
    is_readed = models.BooleanField('Прочитано', default=False)
    sender_visibility = models.BooleanField('Отображение у отправителя', default=True)
    reciever_visibility = models.BooleanField('Отображение у получателя', default=True)

    def __str__(self):
        return str(self.sender) + ' to ' + str(self.reciever)

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'

social_network/apps/posts/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    post_title = models.CharField('Заголовок', max_length = 150, blank = True)
    post_text = models.TextField('Текст поста')
    post_image = models.ImageField('Изображение поста', blank = True, upload_to = 'images/post/')
    post_image_url = models.ImageField('URL изображения поста', blank = True)
    post_time = models.DateTimeField('Время создания')
    post_like = models.ManyToManyField(User,
                                        related_name='post_liked',
                                        blank=True)
    post_dislike = models.ManyToManyField(User,
                                        related_name='post_disliked',
                                        blank=True)

    def __str__(self):
        return str(self.author)

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Like(models.Model):
    LIKE_OR_DISLAKE_CHOICES = (
    ("LIKE", "like"),
    ("DISLIKE", "dislike"),
    (None, "None")
    )

    user = models.ForeignKey(User, on_delete = models.CASCADE)
    for_post = models.ForeignKey(Post, on_delete = models.CASCADE)
    like_or_dislike = models.CharField(max_length=7,
                  choices=LIKE_OR_DISLAKE_CHOICES,
                  default=None)

    class Meta:
        verbose_name = 'Лайк'
        verbose_name_plural = 'Лайки'


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete = models.CASCADE, related_name="post_comments")
    comment_author = models.ForeignKey(User, on_delete = models.CASCADE)
    comment_text = models.CharField('Текст комментария', max_length = 350)
    comment_pubdate = models.DateTimeField('Дата публикации')

    def __str__(self):
        return self.comment_text

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

social_network/apps/account/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import Profile

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ('avatar', 'gender', 'city', 'birth_date')

social_network/apps/posts/forms.py
from django.forms import ModelForm, Textarea
from .models import Post

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('post_title', 'post_text', 'post_image')
        widgets = {
            'post_text': Textarea(attrs={'rows': 3}),
        }

social_network/apps/account/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.urls import reverse
from django.contrib.auth.models import User
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required
from .models import Friend, Follower
from posts.forms import PostForm
from posts.models import Post
from django.utils import timezone
from .forms import ProfileForm
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


#Аккаунт пользователя
@login_required(login_url = '/')
def user_account(request):
    username = request.user
    user = User.objects.get(username = username)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.post_time = timezone.now()
            new_post.save()
            return HttpResponseRedirect(request.path)
    else:
        form = PostForm()

    user_posts = Post.objects.filter(author = user).order_by("-post_time")
    page = request.GET.get('page', 1)
    paginator = Paginator(user_posts, 10)
    try:
      post_list = paginator.page(page)
    except PageNotAnInteger:
      post_list = paginator.page(1)
    except EmptyPage:
      post_list = paginator.page(paginator.num_pages)

    followers = Follower.objects.filter(follower_for = request.user)
    context = {'user': user, 'form':form, 'user_posts': post_list, 'followers': followers}
    return render(request, 'account/account.html', context)

#Изменение аватара пользователя
@login_required(login_url = '/')
def account_setting(request):
    user_set = User.objects.get(id = request.user.id)
    print(user_set.profile.city)
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=user_set.profile)
        if form.is_valid():
            user_setting = request.user
            first_name = request.POST.get('first_name')
            last_name = request.POST.get('last_name')
            avatar = form.cleaned_data['avatar']
            gender = form.cleaned_data['gender']
            city = form.cleaned_data['city']
            birth_date = form.cleaned_data['birth_date']
            if avatar:
                user_setting.profile.avatar = avatar
            else:
                user_setting.profile.avatar = 'images/avatar/standart.jpg'
            user_setting.profile.gender = gender
            user_setting.profile.city = city
            user_setting.profile.birth_date = birth_date
            if first_name:
                user_setting.first_name = first_name
            if last_name:
                user_setting.last_name = last_name
            user_setting.save()
            return HttpResponseRedirect(reverse('account:user_account'))
    else:
        form = ProfileForm(instance=user_set.profile)
    context = {'form': form}
    return render(request, 'account/setting.html', context)


@login_required(login_url = '/')
def friends(request):
    users_friends1 = Friend.objects.filter(user = request.user, confirmed = True)
    users_friends2 = Friend.objects.filter(users_friend = request.user, confirmed = True)
    new_friends = Friend.objects.filter(users_friend = request.user, confirmed = False).count()
    context = {"friends1": users_friends1, "friends2": users_friends2, "not_confirmed_friends_count": new_friends}
    return render(request, 'account/friends.html', context)


@login_required(login_url = '/')
def friend_request(request):
    not_confirmed_friends = Friend.objects.filter(users_friend = request.user, confirmed = False)
    new_friends = Friend.objects.filter(users_friend = request.user, confirmed = False).count()
    context = {"not_confirmed_friends": not_confirmed_friends, "not_confirmed_friends_count": new_friends}
    return render(request, 'account/friend_request.html', context)


@login_required(login_url = '/')
def add_friend(request, account_id):
    try:
        user = User.objects.get(id = account_id)
    except:
        raise Http404("Пользователь не найден!")

    is_friend = Friend.objects.filter(user = request.user, users_friend = user)|Friend.objects.filter(user = user, users_friend = request.user)
    if not is_friend:
        add_friend = Friend(user = request.user, users_friend = user)
        add_friend.save()
    return HttpResponseRedirect(reverse('account:account', args = (account_id, )))


@login_required(login_url = '/')
def confirm_friend(request, account_id):
    try:
        user = User.objects.get(id = account_id)
    except:
        raise Http404("Пользователь не найден!")

    new_friend = Friend.objects.get(user = user, users_friend = request.user)
    new_friend.confirmed = True
    new_friend.save()
    return HttpResponseRedirect(reverse('account:friends'))


@login_required(login_url = '/')
def delete_friend(request, account_id):
    try:
        user = User.objects.get(id = account_id)
    except:
        raise Http404("Пользователь не найден!")

    new_friend = Friend.objects.filter(user = user, users_friend = request.user)|Friend.objects.filter(user = request.user, users_friend = user )
    new_friend.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


#Поиск/отображение всех пользователей
@login_required(login_url = '/')
def find_users(request):
    if request.method == 'POST':
        user_setting = request.user
        search = request.POST.get('search')
        queryset = User.objects.all().exclude(username = request.user)
        if search:
            search_list = search.split(' ')
            if len(search_list) == 2:
                users = queryset.filter(Q(first_name__iexact=search_list[0]) & Q(last_name__iexact=search_list[1])|Q(first_name__iexact=search_list[1]) & Q(last_name__iexact=search_list[0]))
            elif len(search_list) == 1:
                users = queryset.filter(Q(first_name__iexact=search_list[0]) | Q(last_name__iexact=search_list[0]))
            else:
                users = False
        else:
            users = False
    else:
        users = User.objects.all().exclude(username = request.user).order_by("-id")[:20]
    new_friends = Friend.objects.filter(users_friend = request.user, confirmed = False).count()
    context = {
        'users': users,
        "not_confirmed_friends_count": new_friends
    }
    return render(request, 'account/users.html', context)


#Переход на аккаунт другого пользователя
@login_required(login_url = '/')
def account(request, account_id):
    try:
        user = User.objects.get(id = account_id)
    except:
        raise Http404("Пользователь не найден!")

    if Friend.objects.filter(user = request.user, users_friend = user)|Friend.objects.filter(user = user, users_friend = request.user):
        is_friend = False
    else:
        is_friend = True

    if Follower.objects.filter(user = request.user, follower_for = user):
        is_follower = False
    else:
        is_follower = True

    users_friends1 = Friend.objects.filter(user = user, confirmed = True)#[:6]
    users_friends2 = Friend.objects.filter(users_friend = user, confirmed = True)#[:6-len(users_friends1)]

    user_posts = Post.objects.filter(author = user).order_by("-post_time")
    page = request.GET.get('page', 1)
    paginator = Paginator(user_posts, 10)
    try:
      post_list = paginator.page(page)
    except PageNotAnInteger:
      post_list = paginator.page(1)
    except EmptyPage:
      post_list = paginator.page(paginator.num_pages)

    user_following = Follower.objects.filter(user = user)
    context = {'other_user': user, 'user_posts': post_list, 'is_friend': is_friend, "friends1": users_friends1, "friends2": users_friends2, 'is_follower': is_follower, 'user_following': user_following}
    return render(request, 'account/id.html', context)


@login_required(login_url = '/')
def add_follower(request, account_id):
    try:
        user = User.objects.get(id = account_id)
    except:
        raise Http404("Пользователь не найден!")

    is_follower = Follower.objects.filter(user = request.user, follower_for = user)
    if not is_follower:
        add_follower = Follower(user = request.user, follower_for = user)
        add_follower.save()
    return HttpResponseRedirect(reverse('account:account', args = (account_id, )))


@login_required(login_url = '/')
def delete_follower(request, account_id):
    try:
        user = User.objects.get(id = account_id)
    except:
        raise Http404("Пользователь не найден!")

    follower = Follower.objects.filter(user = request.user, follower_for = user)
    follower.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

social_network/apps/bots/views.py
from django.shortcuts import render
import requests

# Create your views here.
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, Http404, HttpResponse, JsonResponse
from django.urls import reverse
from django.contrib.auth.models import User
from posts.models import Post
from django.utils import timezone
from django.contrib.auth.decorators import login_required

def create_post(request):
    user = User.objects.get(username = 'bot')
    #token не работает, так как подкорректирован. У вас должен быть свой
    token = 'f88de38bf88de38bf88de38bd3f8fc7a6fff88df88de38ba620dc9725559b497361de40'
    version = 5.103
    domain = 'tproger'

    response = requests.get('https://api.vk.com/method/wall.get',
                            params={
                            'access_token': token,
                            'v': version,
                            'domain': domain,
                            'count': 5
                            }
                        )
    data = response.json()['response']['items']
    for news in data:
        try:
            if news['attachments'][0]['type']:
                img_url = news['attachments'][0]['photo']['sizes'][-1]['url']
            else:
                img_url = ''
        except:
            img_url = ''

        try:
            news['attachments'][0]['video']
        except:
            if news['text'] != '':
                in_post = Post.objects.filter(post_text = news['text'])
            else:
                in_post = Post.objects.filter(post_image_url = img_url)

            if not in_post:
                post = Post(author = user, post_text=news['text'], post_time = timezone.now(), post_image_url=img_url)
                post.save()

    return HttpResponse('Complete ')

social_network/templates/dialogs/dialog.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Диалог с {{friend.first_name}} {{friend.last_name}} {% endblock %}
{% block style %}
<link href="{% static 'css/dialogs/dialog.css' %}" rel="stylesheet">
{% endblock %}
{% block main %}
  {% include 'menu.html' %}
   <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="main col-12 col-sm-12 col-md-10 col-lg-8 col-xl-6 ">
        <div id='message_block' class="messages">
          {% if messages2 %}
            <a href="#" id="previous_messages">Предыдущие сообщения</a>
          {% endif %}
          {% for message in sort_messages %}
            {% if message.sender == request.user %}
                <div class="media w-75 bg-secondary mb-3 p-1 rounded" id='message{{message.id}}'>
                  <a href="{% url 'account:user_account' %}">
                  <img class="d-flex mr-3" src="{{ message.sender.profile.avatar.url }}" width="40px" alt="{{ message.sender.first_name }}"></a>
                  <div class="media-body">
                    <h6 class="mt-0 wordwrap textowerflow">{{message.sender.first_name}} {{message.sender.last_name}} <time class="float-right">{{message.message_time}}</time></h6>
                    <div class="wordwrap textowerflow">
                      {{message.message_text|linebreaks|urlizetrunc:30}}
                    </div>
                    <a class="close delete_message pb-1" href="#" data-id="message{{message.id}}" data-action="{{message.id}}" title="Удалить">
                      <span aria-hidden="true" class="text-danger m-1" >&times;</span>
                    </a>
                  </div>
                </div>
            {% else %}
                <div class="media w-75 float-right bg-success mb-3 mr-1 p-1 rounded" id='message{{message.id}}'>
                  <div class="media-body">
                    <h6 class="mt-0 mb-1 wordwrap textowerflow">{{message.sender.first_name}} {{message.sender.last_name}} <time class="float-right">{{message.message_time}}</time></h6>
                    <div class="wordwrap textowerflow">
                      {{message.message_text|linebreaks|urlizetrunc:30}}
                    </div>
                    <a class="close delete_message pb-1" href="#" data-id="message{{message.id}}" data-action="{{message.id}}" title="Удалить">
                      <span aria-hidden="true" class="text-danger m-1" >&times;</span>
                    </a>
                  </div>
                  <a href="{% url 'account:account' message.sender.id %}"><img class="d-flex ml-3" src="{{ message.sender.profile.avatar.url }}" width="40px" alt="{{ message.sender.first_name }}"></a>
                </div>
            {% endif %}
          {% endfor %}
        </div>
          <form id="leave_message" enctype="multipart/form-data" class="form-inline mt-2">
            {% csrf_token %}
            <textarea name="message_text" id="message_text" rows="2" maxlength="500"></textarea>
            <button type="submit" name="button" class="btn-primary">Отправить</button>
          </form>
        <!-- <a href="{% url 'dialogs:messages' %}">Назад</a> -->
      </div>
      </div>
    </div>


  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script type="text/javascript">
    window.onload = function(){ document.getElementById('message_block').scrollTop = 9999;}

    setInterval(function () {
          $.ajax({
              url: "{% url 'dialogs:post' friend.username %}",
              type: 'GET',
              data: {'check': true},

              success: function (json) {
                  if (json.result) {
                      var doc = $.parseHTML(json.messages_list);
                      $('#message_block').append(doc);
                      $('#message_block').scrollTop(9999);
                  }
              }
          });
      }, 1000);

      $(document).on('submit', '#leave_message', function(e){
        e.preventDefault();
        var message_text = $('#message_text').val();
        if (message_text != ''){
           $('#message_text').val('');
           $.ajax({
            type:'POST',
            url:'{% url "dialogs:leave_message" friend.username %}',
            data:{
              message_text:message_text,
              csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
            },
            success:function (json) {
                if (json.result) {
                    var doc = $.parseHTML(json.messages_list);
                    $('#message_block').append(doc);
                    $('#message_block').scrollTop(9999);
              }
            }
          });
        };
      });


      $('#previous_messages').on('click', function(e) {
        e.preventDefault();
        var message_block = $('#message_block');
        message_block.scrollTop(message_block.get(0).scrollHeight);
        var scrollHeight = message_block.scrollTop() + message_block.height();
        message_block.scrollTop(0);

        $('#previous_messages').remove();
           {% for message in messages2 %}
             {% if message.sender == request.user %}
                message_block.prepend('<div class="media w-75 bg-secondary mb-3 p-1 rounded"><img class="d-flex mr-3" src="{{ message.sender.profile.avatar.url }}" width="40px" alt="{{ message.sender.first_name }}"><div class="media-body wordwrap textowerflow"><h6 class="mt-0 wordwrap textowerflow">{{message.sender.first_name}} {{message.sender.last_name}} <time class="float-right">{{message.message_time}}</time></h6>{{message.message_text|linebreaks|urlizetrunc:30}}</div></div>');
             {% else %}
               message_block.prepend('<div class="media w-75 float-right bg-success mb-3 mr-1 p-1 rounded"><div class="media-body wordwrap textowerflow"><h6 class="mt-0 mb-1 wordwrap textowerflow">{{message.sender.first_name}} {{message.sender.last_name}} <time class="float-right">{{message.message_time}}</time></h6>{{message.message_text|linebreaks|urlizetrunc:30}}</div><img class="d-flex ml-3" src="{{ message.sender.profile.avatar.url }}" width="40px" alt="{{ message.sender.first_name }}"></div>');
             {% endif %}
           {% endfor %}
        message_block.scrollTop(message_block.get(0).scrollHeight);
        var new_scrollHeight = message_block.scrollTop() + message_block.height();
        message_block.scrollTop(0);
        message_block.scrollTop(new_scrollHeight - scrollHeight);
       });

       $('a.delete_message').on('click', function(e){
          e.preventDefault();
          var delete_message = $(this).data('id');
          var message_id = parseInt($(this).data('action'));
          $.get(
            '/message'+message_id+'/delete',
            function(data){
              if (data['status'] == 'ok'){
                $('#'+delete_message).remove();
               }
            });
        });
    </script>
{% endblock %}

social_network/templates/dialogs/messages.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Диалоги {% endblock %}
{% block style %}
<link href="{% static 'css/dialogs/messages.css' %}" rel="stylesheet">
{% endblock %}
{% block main %}
{% include 'menu.html' %}
<div class="container-fluid">
 <div class="row justify-content-center">
   <div class="main col-12 col-sm-12 col-md-10 col-lg-8 col-xl-6 ">
     {% if not messages %}
        <div class="text-center">
          <h5>У вас пока нет сообщений.</h5>
        </div>
        {% if friends1 or friends2 %}
          <div class="text-left">
            <p>
              Вы можете написать своему другу.</p>
          </div>
          <div class="card-columns">
              {% for friend in friends1 %}
                <div class="card">
                  <a href="{% url 'account:account' friend.users_friend.id %}"><img src="{{ friend.users_friend.profile.avatar.url }}" alt="{{ friend.users_friend.username }}" class="card-img-top"></a>
                  <div class="card-body">
                    <h4 class="card-title wordwrap textowerflow"><a href="{% url 'account:account' friend.users_friend.id %}">
                    {{ friend.users_friend.first_name }} {{ friend.users_friend.last_name }}</a></h4>
                    <a class="btn btn-primary" href="{% url 'dialogs:dialog' friend.users_friend.username %}">Написать</a>
                  </div>
                </div>
              {% endfor %}
              {% for friend in friends2 %}
                <div class="card">
                  <a href="{% url 'account:account' friend.user.id %}"><img src="{{ friend.user.profile.avatar.url }}" alt="{{ friend.user.username }}" class="card-img-top"></a>
                  <div class="card-body">
                    <h4 class="card-title wordwrap textowerflow"><a href="{% url 'account:account' friend.user.id %}">
                    {{ friend.user.first_name }} {{ friend.user.last_name }}</a></h4>
                    <a class="btn btn-primary" href="{% url 'dialogs:dialog' friend.user.username %}">Написать</a>
                  </div>
                </div>
              {% endfor %}
              </div>
        {% endif %}
     {% endif %}
     {% for message in messages %}
         {% if message.sender == request.user %}
           <a href="{% url 'dialogs:dialog' message.reciever.username %}" id="dialog{{message.reciever.id}}">
             <div class="media bg-secondary mt-3 p-2 rounded">
               <img class="d-flex mr-3 mes-img" src="{{ message.reciever.profile.avatar.url }}" width="50px" alt="{{ message.reciever.first_name }}" >
               <div class="media-body wordwrap textowerflow">
                 <h5 class="mt-0 wordwrap textowerflow"><strong>{{ message.reciever.first_name }} {{message.reciever.last_name}}</strong>
                   <time class="float-right">{{message.message_time}}</time></h5>
                   <div class="wordwrap textowerflow">
                     {{message.message_text|linebreaks|truncatewords_html:25}}
                   </div>
                   <button type="button" name="button" class="delete_dialog btn btn-sm btn-primary float-right mb-1 mr-1" data-id="dialog{{message.reciever.id}}" data-action="{{message.reciever.id}}">Удалить диалог</button>
               </div>
             </div>
            </a>
         {% else %}
          {% if not message.is_readed %}
            <a href="{% url 'dialogs:dialog' message.sender.username %}" id="dialog{{message.sender.id}}">
              <div class="media bg-info mt-3 p-2 rounded">
                <img class="d-flex mr-3 mes-img" src="{{ message.sender.profile.avatar.url }}" width="50px" alt="{{ message.sender.first_name }}" >
                <div class="media-body wordwrap textowerflow">
                  <h5 class="mt-0 wordwrap textowerflow">{{ message.sender.first_name }} {{message.sender.last_name}}
                    <time class="float-right">{{message.message_time}}</time></h5>
                    <div class="wordwrap textowerflow">
                      {{message.message_text|linebreaks|truncatewords_html:25}}
                    </div>
                    <button type="button" name="button" class="delete_dialog btn btn-sm btn-primary float-right mb-1 mr-1" data-id="dialog{{message.sender.id}}" data-action="{{message.sender.id}}">Удалить диалог</button>
                </div>
              </div>
            </a>
          {% else %}
            <a href="{% url 'dialogs:dialog' message.sender.username %}" id="dialog{{message.sender.id}}">
              <div class="media bg-secondary mt-3 p-2 rounded">
                <img class="d-flex mr-3 mes-img" src="{{ message.sender.profile.avatar.url }}" width="50px" alt="{{ message.sender.first_name }}" >
                <div class="media-body wordwrap textowerflow">
                  <h5 class="mt-0 wordwrap textowerflow">{{ message.sender.first_name }} {{message.sender.last_name}}
                    <time class="float-right">{{message.message_time}}</time></h5>
                    <div class="wordwrap textowerflow">
                      {{message.message_text|linebreaks|truncatewords_html:25}}
                    </div>
                    <button type="button" name="button" class="delete_dialog btn btn-sm btn-primary float-right mb-1 mr-1" data-id="dialog{{message.sender.id}}" data-action="{{message.sender.id}}">Удалить диалог</button>
                </div>
              </div>
            </a>
          {% endif %}
         {% endif %}
       {% endfor %}
     </div>
   </div>
 </div>

 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
 <script type="text/javascript">
      $('button.delete_dialog').on('click', function(e){
         e.preventDefault();
         var delete_dialog = $(this).data('id');
         var companion_id = parseInt($(this).data('action'));
         $.get(
           '/dialog'+companion_id+'/delete',
           function(data){
             if (data['status'] == 'ok'){
               $('#'+delete_dialog).remove();
              }
           });
       });
   </script>

{% endblock %}