social_network/apps/account/urls.py
from django.urls import path
from django.contrib.auth import views as standart_views

from . import views

app_name = 'account'
urlpatterns = [
    path('account/', views.user_account, name = 'user_account'),
    path('account_setting/', views.account_setting, name = 'account_setting'),
    path('friends/', views.friends, name = 'friends'),
    path('friend_request/', views.friend_request, name = 'friend_request'),
    path('id<int:account_id>/add_friend', views.add_friend, name = 'add_friend'),
    path('id<int:account_id>/add_follower', views.add_follower, name = 'add_follower'),
    path('confirm_friend<int:account_id>/', views.confirm_friend, name = 'confirm_friend'),
    path('delete_friend<int:account_id>/', views.delete_friend, name = 'delete_friend'),
    path('delete_follower<int:account_id>/', views.delete_follower, name = 'delete_follower'),
    path('users/', views.find_users, name = 'find_users'),
    path('id<int:account_id>/', views.account, name = 'account'),
    ]

social_network/apps/bots/urls.py
from django.urls import path

from . import views

app_name = 'bots'
urlpatterns = [
    path('create_post/', views.create_post, name = 'create_post'),
    ]

social_network/apps/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('delete<int:post_id>/', views.delete_post, name = 'delete_post'),
    path('edit_post<int:post_id>/', views.edit_post, name = 'edit_post'),
    path('news/', views.news, name = 'news'),
    path('like_news/', views.like_news, name = 'like_news'),
    path('friend_news/', views.friend_news, name = 'friend_news'),
    path('news/like/', views.like_or_dislike, name = 'like_or_dislike'),
    path('news/user_like', views.user_like, name = 'user_like'),
    path('news<int:post_id>/leave_comment', views.leave_comment, name = 'leave_comment'),
    path('comment<int:comment_id>/delete', views.delete_comment, name = 'delete_comment'),
    path('news<int:post_id>/', views.post, name = 'post'),
    path('back/', views.back, name = 'back'),
]

social_network/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('registration.urls')),
    path('', include('account.urls')),
    path('', include('dialogs.urls')),
    path('', include('posts.urls')),
    path('', include('bots.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social_network/apps/bots/models.py
from django.db import models

# Create your models here.

social_network/apps/dialogs/models.py
from django.db import models
from django.contrib.auth.models import User


class Message(models.Model):
    sender = models.ForeignKey(User, on_delete = models.DO_NOTHING)
    reciever = models.ForeignKey(User, related_name = 'to_reciever', on_delete = models.DO_NOTHING)
    message_text = models.TextField('Текст сообщения')
    message_image = models.ImageField('Изображение', blank = True, upload_to = 'images/messages/')
    message_time = models.DateTimeField('Время отправления')
    is_readed = models.BooleanField('Прочитано', default=False)
    sender_visibility = models.BooleanField('Отображение у отправителя', default=True)
    reciever_visibility = models.BooleanField('Отображение у получателя', default=True)

    def __str__(self):
        return str(self.sender) + ' to ' + str(self.reciever)

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'

social_network/apps/posts/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    post_title = models.CharField('Заголовок', max_length = 150, blank = True)
    post_text = models.TextField('Текст поста')
    post_image = models.ImageField('Изображение поста', blank = True, upload_to = 'images/post/')
    post_image_url = models.ImageField('URL изображения поста', blank = True)
    post_time = models.DateTimeField('Время создания')
    post_like = models.ManyToManyField(User,
                                        related_name='post_liked',
                                        blank=True)
    post_dislike = models.ManyToManyField(User,
                                        related_name='post_disliked',
                                        blank=True)

    def __str__(self):
        return str(self.author)

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Like(models.Model):
    LIKE_OR_DISLAKE_CHOICES = (
    ("LIKE", "like"),
    ("DISLIKE", "dislike"),
    (None, "None")
    )

    user = models.ForeignKey(User, on_delete = models.CASCADE)
    for_post = models.ForeignKey(Post, on_delete = models.CASCADE)
    like_or_dislike = models.CharField(max_length=7,
                  choices=LIKE_OR_DISLAKE_CHOICES,
                  default=None)

    class Meta:
        verbose_name = 'Лайк'
        verbose_name_plural = 'Лайки'


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete = models.CASCADE, related_name="post_comments")
    comment_author = models.ForeignKey(User, on_delete = models.CASCADE)
    comment_text = models.CharField('Текст комментария', max_length = 350)
    comment_pubdate = models.DateTimeField('Дата публикации')

    def __str__(self):
        return self.comment_text

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

social_network/apps/account/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import Profile

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ('avatar', 'gender', 'city', 'birth_date')

social_network/apps/posts/forms.py
from django.forms import ModelForm, Textarea
from .models import Post

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('post_title', 'post_text', 'post_image')
        widgets = {
            'post_text': Textarea(attrs={'rows': 3}),
        }

social_network/apps/account/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.urls import reverse
from django.contrib.auth.models import User
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required
from .models import Friend, Follower
from posts.forms import PostForm
from posts.models import Post
from django.utils import timezone
from .forms import ProfileForm
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


#Аккаунт пользователя
@login_required(login_url = '/')
def user_account(request):
    username = request.user
    user = User.objects.get(username = username)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.post_time = timezone.now()
            new_post.save()
            return HttpResponseRedirect(request.path)
    else:
        form = PostForm()

    user_posts = Post.objects.filter(author = user).order_by("-post_time")
    page = request.GET.get('page', 1)
    paginator = Paginator(user_posts, 10)
    try:
      post_list = paginator.page(page)
    except PageNotAnInteger:
      post_list = paginator.page(1)
    except EmptyPage:
      post_list = paginator.page(paginator.num_pages)

    followers = Follower.objects.filter(follower_for = request.user)
    context = {'user': user, 'form':form, 'user_posts': post_list, 'followers': followers}
    return render(request, 'account/account.html', context)

#Изменение аватара пользователя
@login_required(login_url = '/')
def account_setting(request):
    user_set = User.objects.get(id = request.user.id)
    print(user_set.profile.city)
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=user_set.profile)
        if form.is_valid():
            user_setting = request.user
            first_name = request.POST.get('first_name')
            last_name = request.POST.get('last_name')
            avatar = form.cleaned_data['avatar']
            gender = form.cleaned_data['gender']
            city = form.cleaned_data['city']
            birth_date = form.cleaned_data['birth_date']
            if avatar:
                user_setting.profile.avatar = avatar
            else:
                user_setting.profile.avatar = 'images/avatar/standart.jpg'
            user_setting.profile.gender = gender
            user_setting.profile.city = city
            user_setting.profile.birth_date = birth_date
            if first_name:
                user_setting.first_name = first_name
            if last_name:
                user_setting.last_name = last_name
            user_setting.save()
            return HttpResponseRedirect(reverse('account:user_account'))
    else:
        form = ProfileForm(instance=user_set.profile)
    context = {'form': form}
    return render(request, 'account/setting.html', context)


@login_required(login_url = '/')
def friends(request):
    users_friends1 = Friend.objects.filter(user = request.user, confirmed = True)
    users_friends2 = Friend.objects.filter(users_friend = request.user, confirmed = True)
    new_friends = Friend.objects.filter(users_friend = request.user, confirmed = False).count()
    context = {"friends1": users_friends1, "friends2": users_friends2, "not_confirmed_friends_count": new_friends}
    return render(request, 'account/friends.html', context)


@login_required(login_url = '/')
def friend_request(request):
    not_confirmed_friends = Friend.objects.filter(users_friend = request.user, confirmed = False)
    new_friends = Friend.objects.filter(users_friend = request.user, confirmed = False).count()
    context = {"not_confirmed_friends": not_confirmed_friends, "not_confirmed_friends_count": new_friends}
    return render(request, 'account/friend_request.html', context)


@login_required(login_url = '/')
def add_friend(request, account_id):
    try:
        user = User.objects.get(id = account_id)
    except:
        raise Http404("Пользователь не найден!")

    is_friend = Friend.objects.filter(user = request.user, users_friend = user)|Friend.objects.filter(user = user, users_friend = request.user)
    if not is_friend:
        add_friend = Friend(user = request.user, users_friend = user)
        add_friend.save()
    return HttpResponseRedirect(reverse('account:account', args = (account_id, )))


@login_required(login_url = '/')
def confirm_friend(request, account_id):
    try:
        user = User.objects.get(id = account_id)
    except:
        raise Http404("Пользователь не найден!")

    new_friend = Friend.objects.get(user = user, users_friend = request.user)
    new_friend.confirmed = True
    new_friend.save()
    return HttpResponseRedirect(reverse('account:friends'))


@login_required(login_url = '/')
def delete_friend(request, account_id):
    try:
        user = User.objects.get(id = account_id)
    except:
        raise Http404("Пользователь не найден!")

    new_friend = Friend.objects.filter(user = user, users_friend = request.user)|Friend.objects.filter(user = request.user, users_friend = user )
    new_friend.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


#Поиск/отображение всех пользователей
@login_required(login_url = '/')
def find_users(request):
    if request.method == 'POST':
        user_setting = request.user
        search = request.POST.get('search')
        queryset = User.objects.all().exclude(username = request.user)
        if search:
            search_list = search.split(' ')
            if len(search_list) == 2:
                users = queryset.filter(Q(first_name__iexact=search_list[0]) & Q(last_name__iexact=search_list[1])|Q(first_name__iexact=search_list[1]) & Q(last_name__iexact=search_list[0]))
            elif len(search_list) == 1:
                users = queryset.filter(Q(first_name__iexact=search_list[0]) | Q(last_name__iexact=search_list[0]))
            else:
                users = False
        else:
            users = False
    else:
        users = User.objects.all().exclude(username = request.user).order_by("-id")[:20]
    new_friends = Friend.objects.filter(users_friend = request.user, confirmed = False).count()
    context = {
        'users': users,
        "not_confirmed_friends_count": new_friends
    }
    return render(request, 'account/users.html', context)


#Переход на аккаунт другого пользователя
@login_required(login_url = '/')
def account(request, account_id):
    try:
        user = User.objects.get(id = account_id)
    except:
        raise Http404("Пользователь не найден!")

    if Friend.objects.filter(user = request.user, users_friend = user)|Friend.objects.filter(user = user, users_friend = request.user):
        is_friend = False
    else:
        is_friend = True

    if Follower.objects.filter(user = request.user, follower_for = user):
        is_follower = False
    else:
        is_follower = True

    users_friends1 = Friend.objects.filter(user = user, confirmed = True)#[:6]
    users_friends2 = Friend.objects.filter(users_friend = user, confirmed = True)#[:6-len(users_friends1)]

    user_posts = Post.objects.filter(author = user).order_by("-post_time")
    page = request.GET.get('page', 1)
    paginator = Paginator(user_posts, 10)
    try:
      post_list = paginator.page(page)
    except PageNotAnInteger:
      post_list = paginator.page(1)
    except EmptyPage:
      post_list = paginator.page(paginator.num_pages)

    user_following = Follower.objects.filter(user = user)
    context = {'other_user': user, 'user_posts': post_list, 'is_friend': is_friend, "friends1": users_friends1, "friends2": users_friends2, 'is_follower': is_follower, 'user_following': user_following}
    return render(request, 'account/id.html', context)


@login_required(login_url = '/')
def add_follower(request, account_id):
    try:
        user = User.objects.get(id = account_id)
    except:
        raise Http404("Пользователь не найден!")

    is_follower = Follower.objects.filter(user = request.user, follower_for = user)
    if not is_follower:
        add_follower = Follower(user = request.user, follower_for = user)
        add_follower.save()
    return HttpResponseRedirect(reverse('account:account', args = (account_id, )))


@login_required(login_url = '/')
def delete_follower(request, account_id):
    try:
        user = User.objects.get(id = account_id)
    except:
        raise Http404("Пользователь не найден!")

    follower = Follower.objects.filter(user = request.user, follower_for = user)
    follower.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

social_network/apps/bots/views.py
from django.shortcuts import render
import requests

# Create your views here.
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, Http404, HttpResponse, JsonResponse
from django.urls import reverse
from django.contrib.auth.models import User
from posts.models import Post
from django.utils import timezone
from django.contrib.auth.decorators import login_required

def create_post(request):
    user = User.objects.get(username = 'bot')
    #token не работает, так как подкорректирован. У вас должен быть свой
    token = 'f88de38bf88de38bf88de38bd3f8fc7a6fff88df88de38ba620dc9725559b497361de40'
    version = 5.103
    domain = 'tproger'

    response = requests.get('https://api.vk.com/method/wall.get',
                            params={
                            'access_token': token,
                            'v': version,
                            'domain': domain,
                            'count': 5
                            }
                        )
    data = response.json()['response']['items']
    for news in data:
        try:
            if news['attachments'][0]['type']:
                img_url = news['attachments'][0]['photo']['sizes'][-1]['url']
            else:
                img_url = ''
        except:
            img_url = ''

        try:
            news['attachments'][0]['video']
        except:
            if news['text'] != '':
                in_post = Post.objects.filter(post_text = news['text'])
            else:
                in_post = Post.objects.filter(post_image_url = img_url)

            if not in_post:
                post = Post(author = user, post_text=news['text'], post_time = timezone.now(), post_image_url=img_url)
                post.save()

    return HttpResponse('Complete ')

social_network/templates/posts/create_comment.html
<div class="media w-100 bg-success mb-3 p-1 rounded" id="comment{{comment.id}}">
  <a href="{% url 'account:account' comment.comment_author.id %}">
   <img class="d-flex mr-3 rounded-circle" src="{{ comment.comment_author.profile.avatar.url }}" width="40px" alt="{{ comment.comment_author.first_name }}">
</a>
  <div class="media-body">
    <h6 class="mt-0 wordwrap textowerflow">{{comment.comment_author.first_name}} {{comment.comment_author.last_name}} <time class="float-right">{{comment.comment_pubdate}}</time></h6>
    <div class="wordwrap textowerflow">
      {{comment.comment_text|linebreaks|urlizetrunc:30}}
    </div>
    <!-- <a href="#" class="delete_comment btn btn-primary float-right mb-1 mr-1" data-id="comment{{comment.id}}" data-action="{{comment.id}}" >Удалить</a> -->
  </div>
</div>

social_network/templates/posts/edit_post.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Настройки аккаунта {% endblock %}

{% block style %}
<link href="{% static 'css/posts/edit_post.css' %}" rel="stylesheet">
{% endblock %}

{% block main %}
{% include 'menu.html' %}
<div class="container-fluid">
 <div class="row justify-content-center">
   <div class="main col-12 col-sm-12 col-md-10 col-lg-8 col-xl-6 ">
     <form action="{% url 'posts:edit_post' post.id %}" method="post" enctype="multipart/form-data" class="mt-3 ml-3">
       {% csrf_token %}
       {% for field in form %}
        <div class="form-group">
         {{ field.label_tag}} {{field}}
         <small class="text-danger">{{ field.errors }}</small>
        </div>
       {% endfor %}
       <button type="submit" name="button" class="btn btn-block btn-primary">Сохранить</button>
     </form>
     <hr>
     <a href="{% url 'account:user_account' %}" class="btn btn-danger float-right">Отмена</a>
   </div>
   </div>
 </div>

{% endblock %}

social_network/templates/posts/friend_news.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Новости {% endblock %}
{% block style %}
<link href="{% static 'css/account/id.css' %}" rel="stylesheet">
<link href="{% static 'css/posts/post_columns.css' %}" rel="stylesheet">
<link href="{% static 'css/posts/post_img.css' %}" rel="stylesheet">
{% endblock %}

{% block main %}
  {% include 'menu.html' %}
  <div class="container-fluid text-center">
    <div class="row content">
      <div class="col-md-2 sidenav">
        <div class="category-wrap">
          <ul>
            <li><a href="{% url 'posts:news' %}">Все новости</a></li>
            <li><a href="{% url 'posts:like_news' %}">Понравившиеся</a></li>
            <li class="active"><a href="{% url 'posts:friend_news' %}">Ваши новости</a></li>
          </ul>
        </div>
        <div class="category-wrap">
          <h6>Подписки</h6>
          <div>
            {% for follow_user in follow_list %}
              <div class="friend_block">
                <strong class="card-title wordwrap textowerflow"><a href="{% url 'account:account' follow_user.follower_for.id %}">
                {{ follow_user.follower_for.first_name }} {{ follow_user.follower_for.last_name }}</a></strong>
                <a href="{% url 'account:account' follow_user.follower_for.id %}"><img src="{{ follow_user.follower_for.profile.avatar.url }}" alt="{{ follow_user.follower_for.first_name }}" class="rounded-circle w-100"></a>
                <a href="{% url 'account:delete_follower' follow_user.follower_for.id %}" class="text-primary">Отписаться</a>
              </div>
            {% endfor %}
          </div>
        </div>
      </div>

      <div class="col-md-8 text-left">
        <div class="card-columns p-2">
        {% for post in posts %}
          <div class="card mt-2 text-white bg-dark">
            <div class="card-header wordwrap textowerflow">
                <a href="{% url 'account:account' post.author.id %}" class="text-white">{{ post.author.first_name }} {{ post.author.last_name }}</a>
            </div>
            {% with total_likes=post.post_like.count users_like=post.post_like.all total_dislikes=post.post_dislike.count users_dislike=post.post_dislike.all%}

            {% if post.post_image %}
              <img class="card-img-top" src="{{ post.post_image.url }}" alt="{{ post.post_title }}">
            {% endif %}
            {% if post.post_image_url %}
              <img class="card-img-top" src="{{ post.post_image_url }}" alt="{{ post.post_title }}">
            {% endif %}
              <div class="card-body">
                <div class="wordwrap textowerflow">
                  {% if post.post_title %}
                    <h4 class="card-title">{{ post.post_title }}</h4>
                  {% endif %}
                  <p class="card-text">
                    {{ post.post_text|linebreaks|urlizetrunc:30|truncatewords_html:25 }}

                  </p>
                </div>
              <strong><time>{{ post.post_time }}</time></strong>
              <p>
                {% if post.post_comments.count > 0 %}
                  <a href="{% url 'posts:post' post.id %}" id="comment{{ post.id }}"  class="btn btn-info float-left mr-2">
                    <img id="comment_img{{ post.id }}" src="{{ MEDIA_URL }}static/image/comment.png" alt="comment" width="23px">
                    <strong id="comment_val{{ post.id }}">{{post.post_comments.count}}</strong>
                  </a>
                {% else %}
                  <a href="{% url 'posts:post' post.id %}" id="comment{{ post.id }}"  class="btn btn-secondary float-left mr-2">
                    <img id="comment_img{{ post.id }}" src="{{ MEDIA_URL }}static/image/comment.png" alt="comment" width="23px">
                    <strong id="comment_val{{ post.id }}">{{post.post_comments.count}}</strong>
                  </a>
                {% endif %}

                {% if request.user in users_dislike %}
                  <a href="#" id="dislike_block{{ post.id }}"  class="btn btn-danger float-right ml-2" data-action="undislike" data-id="{{ post.id }}">
                    <img id="dislike_img{{ post.id }}" src="{{ MEDIA_URL }}static/image/dislike.png" alt="dislike" width="20px">
                    <strong id="dislike_val{{ post.id }}">{{total_dislikes}}</strong>
                  </a>
                {% else %}
                  <a href="#" id="dislike_block{{ post.id }}"  class="btn btn-secondary float-right ml-2" data-action="dislike" data-id="{{ post.id }}">
                    <img id="dislike_img{{ post.id }}" src="{{ MEDIA_URL }}static/image/dislike.png" alt="dislike" width="20px">
                    <strong id="dislike_val{{ post.id }}">{{total_dislikes}}</strong>
                  </a>
                {% endif %}

                {% if request.user in users_like %}
                  <a href="#" id="like_block{{ post.id }}" class="btn btn-success float-right ml-2" data-action="unlike" data-id="{{ post.id }}">
                    <img id="like_img{{ post.id }}" src="{{ MEDIA_URL }}static/image/like.png" alt="like" width="20px">
                    <strong id="like_val{{ post.id }}">{{total_likes}}</strong>
                  </a>
                {% else %}
                  <a href="#" id="like_block{{ post.id }}" class="btn btn-secondary float-right ml-2" data-action="like" data-id="{{ post.id }}">
                    <img id="like_img{{ post.id }}" src="{{ MEDIA_URL }}static/image/like.png" alt="like" width="20px">
                    <strong id="like_val{{ post.id }}">{{total_likes}}</strong>
                  </a>
                {% endif %}
                <br>
              </p>
            </div>
          </div>
          {% endwith %}
          <script type="text/javascript">

            $('#like_block{{ post.id }}').on('click', function(e){
              e.preventDefault();
              $.post(
                '{% url "posts:like_or_dislike" %}',
                {id: $(this).data('id'),action: $(this).data('action')},
                function(data){
                  if (data['status'] == 'ok'){
                    var previous_action = $('#like_block{{ post.id }}').data('action');
                    var dislike_previous_action = $('#dislike_block{{ post.id }}').data('action');
                    // Изменяем переменную действия.
                    $('#like_block{{ post.id }}').data('action', previous_action == 'like' ?'unlike' : 'like');
                    $('#dislike_block{{ post.id }}').data('action', 'dislike')
                    // Изменяем цвет ссылки.
                    $('#like_block{{ post.id }}').attr('class', previous_action == 'like' ? 'btn btn-success float-right ml-2' : 'btn btn-secondary float-right ml-2');
                    $('#dislike_block{{ post.id }}').attr('class', 'btn btn-secondary float-right ml-2');
                    //$('a.like').text(previous_action == 'like' ? 'Unlike' : 'Like');
                    // Обновляем общее количество лайков.
                    var previous_likes = parseInt($('#like_val{{ post.id }}').text());
                    $('#like_val{{ post.id }}').text(previous_action == 'like' ? previous_likes + 1 : previous_likes - 1);
                    var previous_dislikes = parseInt($('#dislike_val{{ post.id }}').text());
                    $('#dislike_val{{ post.id }}').text(dislike_previous_action == 'undislike' ? previous_dislikes - 1 : previous_dislikes );
                  }
                });
              });

              $('#dislike_block{{ post.id }}').on('click', function(e){
                e.preventDefault();
                $.post(
                  '{% url "posts:like_or_dislike" %}',
                  {id: $(this).data('id'),action: $(this).data('action')},
                  function(data){
                    if (data['status'] == 'ok'){
                      var previous_action = $('#dislike_block{{ post.id }}').data('action');
                      var like_previous_action = $('#like_block{{ post.id }}').data('action');
                      // Изменяем переменную действия.
                      $('#dislike_block{{ post.id }}').data('action', previous_action == 'dislike' ?'undislike' : 'dislike');
                      $('#like_block{{ post.id }}').data('action', 'like')
                      // Изменяем цвет ссылки.
                      $('#dislike_block{{ post.id }}').attr('class', previous_action == 'dislike' ? 'btn btn-danger float-right ml-2' : 'btn btn-secondary float-right ml-2');
                      $('#like_block{{ post.id }}').attr('class', 'btn btn-secondary float-right ml-2');
                      //$('a.like').text(previous_action == 'like' ? 'Unlike' : 'Like');
                      // Обновляем общее количество лайков.
                      var previous_dislikes = parseInt($('#dislike_val{{ post.id }}').text());
                      $('#dislike_val{{ post.id }}').text(previous_action == 'dislike' ? previous_dislikes + 1 : previous_dislikes - 1);
                      var previous_likes = parseInt($('#like_val{{ post.id }}').text());
                      $('#like_val{{ post.id }}').text(like_previous_action == 'unlike' ? previous_likes - 1 : previous_likes );
                    }
                  });
                });
            </script>
        {% endfor %}
        </div>
        <nav aria-label="post-pagination">
          <ul class="pagination pagination-lg justify-content-center">
            {% if posts.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page={{ posts.previous_page_number }}">Назад</a>
              </li>
            {% endif %}
            {% if posts.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{ posts.next_page_number }}">Предыдущие</a>
              </li>
            {% endif %}
          </ul>
        </nav>
      </div>


      <div class="col-md-2 sidenav">

      </div>
    </div>
  </div>

{% endblock %}